apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-app-config
  namespace: keycloak
data:
  KEYCLOAK_URL: "https://idp.keycloak.com:31111"
  KEYCLOAK_REALM: "student-mgmt"
  KEYCLOAK_CLIENT_ID: "student-app"
  APP_URL: "http://localhost:32000"
  DATABASE_URL: "postgresql://appuser:apppass@app-postgresql:5432/studentdb"
  REDIS_URL: "redis://redis:6379/0"
  KEYCLOAK_CA_CERT: "/etc/ssl/keycloak/ca.crt"
