apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgresql:5432/keycloak
  KC_HOSTNAME: idp.keycloak.com
  KC_HOSTNAME_STRICT: "true"
  KC_HTTPS_PORT: "8443"
  KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/tls.crt
  KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/tls.key
  KC_CACHE: ispn
  KC_CACHE_STACK: jdbc-ping
  KC_HEALTH_ENABLED: "true"
  KC_HTTP_ENABLED: "false"
  KC_PROXY_HEADERS: xforwarded
