apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - fastapi/deployment.yaml
  - fastapi/service.yaml
  - fastapi/configmap.yaml
  - fastapi/secret.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml
  - postgresql/deployment.yaml
  - postgresql/service.yaml
  - postgresql/secret.yaml
  - redis/deployment.yaml
  - redis/service.yaml
